/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz1sistemasg2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testCalcularValorHora() {
        assertEquals(10000, App.calcularValorHora("C", 2));
        assertEquals(3000, App.calcularValorHora("M", 1));
        assertEquals(9000, App.calcularValorHora("B", 5));
        assertEquals(-1, App.calcularValorHora("C", 0));
    }

    @Test void testCalcularDescuento() {
        assertEquals(0, App.calcularDescuento(10000, 1, 2));
        assertEquals(0, App.calcularDescuento(3000, 2, 1));
        assertEquals(3150, App.calcularDescuento(9000, 1, 5));
        assertEquals(0, App.calcularDescuento(10000, 3, 2));
    }

    @Test void testCalcularFactura() {
        assertEquals(11900, App.calcularFactura(10000, 0));
        assertEquals(3570, App.calcularFactura(3000, 0));
        assertEquals(14458, App.calcularFactura(9000, 3150));
    }
}
